default:
  outputs:
    prd:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      user: "{{ env_var('SNOWFLAKE_SVC_USER') }}"
      password : "{{ env_var('SNOWFLAKE_SVC_PASSWD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      threads: 5
  target: prd
